SELECT * FROM TRANSACCION_PAGO;
SELECT * FROM RESERVA_TEMPORAL;
SELECT * FROM CLIENTE;



DECLARE
    TYPE BOLETA IS RECORD (
        NOMBRE CLIENTE.NOMBRE%TYPE,
        ESTADO_RESERVA RESERVA_TEMPORAL.ESTADO%TYPE,
        MONTO_BRUTO TRANSACCION_PAGO.MONTO_BRUTO%TYPE,
        DESCUENTO TRANSACCION_PAGO.DESCUENTO%TYPE,
        MONTO_FINAL TRANSACCION_PAGO.MONTO_FINAL%TYPE,
        ESTADO_TRANSACCION TRANSACCION_PAGO.ESTADO%TYPE
    );

    v_boleta BOLETA;

BEGIN
    SELECT c.NOMBRE,rt.ESTADO AS ESTADO_RESERVA, tp.MONTO_BRUTO, tp.DESCUENTO, 
    tp.MONTO_FINAL, tp.ESTADO AS ESTADO_TRANSACCION into v_boleta.NOMBRE,
    v_boleta.ESTADO_RESERVA, v_boleta.MONTO_BRUTO, v_boleta.DESCUENTO,
    v_boleta.MONTO_FINAL, v_boleta.ESTADO_TRANSACCION

    FROM CLIENTE c
    INNER JOIN RESERVA_TEMPORAL rt ON rt.CLIENTE_ID = c.CLIENTE_ID
    INNER JOIN TRANSACCION_PAGO tp ON tp.RESERVA_ID = rt.RESERVA_ID
    WHERE tp.TRANSACCION_ID = 1;


    DBMS_OUTPUT.PUT_LINE('*** BOLETA PUNTO TICKET ***');
    DBMS_OUTPUT.PUT_LINE('CLIENTE: ' || V_BOLETA.NOMBRE);
    DBMS_OUTPUT.PUT_LINE('ESTADO DE LA RESERVA: ' || V_BOLETA.ESTADO_RESERVA);
    DBMS_OUTPUT.PUT_LINE('MONTO BRUTO: ' || V_BOLETA.MONTO_BRUTO);
    DBMS_OUTPUT.PUT_LINE('DESCUENTO: ' || V_BOLETA.DESCUENTO);
    DBMS_OUTPUT.PUT_LINE('MONTO FINAL: ' || V_BOLETA.MONTO_FINAL);
    DBMS_OUTPUT.PUT_LINE('ESTADO DE LA TRANSACCIÓN: ' || V_BOLETA.ESTADO_TRANSACCION);
END;
/
